### ISSUE TITLE
warning: passing argument 1 to restrict-qualified parameter aliases with argument 2

### ISSUE THREAD

**Issue by suijingfeng** [artemalive/Quake-III-Arena#13]
https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition/blob/b950deb2dd77d08c0e41cde08c27fcf1ee81bbad/src/engine/renderer/tr_bsp.c#L1214

compile with GCC9 complains:
```
code/renderer_mydev/tr_bsp.c:1232:15: warning: passing argument 1 to restrict-qualified parameter aliases with argument 2 [-Wrestrict]
 1232 |   memcpy( grid->heightLodError, grid->heightLodError, grid->height * 4 );
      |  
```
change to `memcpy( hunkgrid->heightLodError, grid->heightLodError, grid->height * 4 );` ?

**Comment by kennyalive** [comment]
Looks like a valid fix. I've checked it is fixed this way in Quake IO. Still I'm going to leave it as is. The main purpose of the my project is to keep project compilable on Windows and I usually don't try to fix Q3 bugs until they don't cause compiler complains or application instability. It looks like  VS 2017 is fine with this code. If subsequent versions will complain I'll apply the fix you suggested. Thanks for letting me know about this.
