### ISSUE TITLE
It is a shame this isn't an ioquake3 fork.

### ISSUE THREAD

**Issue by quakemmo** [artemalive/Quake-III-Arena#15]
Good work, otherwise.  Will it have any future, without being a fork of ioq3, however?

**Comment by kennyalive** [comment]
Hi, it's a small project that has different goals (very modest) comparing to ioq3, it's basically original q3 source code that you can compile on windows, the goal is to preserve it without major modifications.  Talking about vulkan support, I think someone had already tried to implement it as ioq3 fork but I don't follow that development.

**Comment by quakemmo** [comment]
I understand.

I myself maintain a large fork of ioq3 that will be released to the public at some point.

After seeing your work, I wished it was based off ioq3, so I could port my diffs to your branch, and end up having my project based on your, cleaner, code.  However, this isn't possible because your code is not based on ioq3 but on vanilla Q3.

Good work overall, but if you could do it with ioq3 - maybe working with them - it would probably be so much more *useful*.  Most, if not all, projects will fork ioq3 and not vanilla q3 today.
