### ISSUE TITLE
Exit with error code -4

### ISSUE THREAD

**Issue by xtemp09** [artemalive/Quake-III-Arena#3]
vkQuake runs fine, but quake-ke.exe exits with an error.

quake3-ke.exe +set r_renderAPI 0 runs fine.

Q3 1.32b Kenny edition generic May 29 2017
----- FS_Startup -----
Current search path:
f:\Downloads\Temp\Quake3\baseq3\pak8.pk3 (9 files)
f:\Downloads\Temp\Quake3\baseq3\pak7.pk3 (4 files)
f:\Downloads\Temp\Quake3\baseq3\pak6.pk3 (64 files)
f:\Downloads\Temp\Quake3\baseq3\pak5.pk3 (7 files)
f:\Downloads\Temp\Quake3\baseq3\pak4.pk3 (272 files)
f:\Downloads\Temp\Quake3\baseq3\pak3.pk3 (4 files)
f:\Downloads\Temp\Quake3\baseq3\pak2.pk3 (148 files)
f:\Downloads\Temp\Quake3\baseq3\pak1.pk3 (26 files)
f:\Downloads\Temp\Quake3\baseq3\pak0.pk3 (3538 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpmctf5.pk3 (16 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpmctf3.pk3 (118 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpmctf2.pk3 (57 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpmctf1.pk3 (45 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpma3.pk3 (10 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm9.pk3 (10 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm8.pk3 (13 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm7.pk3 (15 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm6.pk3 (41 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm5.pk3 (7 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm4a.pk3 (74 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm4.pk3 (7 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm3a.pk3 (79 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm3.pk3 (28 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm29.pk3 (78 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm28.pk3 (33 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm27.pk3 (95 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm26_cpmctf4.pk3 (100 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm25.pk3 (59 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm24.pk3 (44 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm23.pk3 (91 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm22.pk3 (60 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm21.pk3 (93 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm20.pk3 (82 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm2.pk3 (14 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm1a.pk3 (57 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm19.pk3 (58 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm18r.pk3 (79 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm18.pk3 (77 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm17.pk3 (71 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm16.pk3 (34 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm15.pk3 (28 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm14.pk3 (86 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm13.pk3 (72 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm12.pk3 (20 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm11a.pk3 (18 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm11.pk3 (15 files)
f:\Downloads\Temp\Quake3\baseq3\map_cpm10.pk3 (16 files)
f:\Downloads\Temp\Quake3/baseq3

----------------------
5972 files in pk3 files
execing default.cfg
execing q3config.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found generic

------- Input Initialization -------
Win32 mouse input initialized.
------------------------------------
----- Client Initialization -----
----- Initializing Renderer ----
-------------------------------
----- Client Initialization Complete -----
----- R_Init -----
Initializing Vulkan subsystem
...calling LoadLibrary('vulkan-1.dll'): succeeded
...setting mode 9: 1600 1200 W
...registered window class
...created window@147,4 (1616x1238)

Active 3D API: Vulkan
Vk api version: 1.0.46
Vk driver version: 1615265792
Vk vendor id: 0x10DE (NVIDIA)
Vk device id: 0x11C6
Vk device type: DISCRETE_GPU
Vk device name: GeForce GTX 650 Ti

MODE: 9, 1600 x 1200 windowed
GAMMA: hardware w/ 0 overbright bits
texturemode: GL_LINEAR_MIPMAP_NEAREST
picmip: 1
texture bits: 32
SetDeviceGammaRamp failed.
----- finished R_Init -----

------- sound initialization -------
Initializing DirectSound
------------------------------------
----- Sound Info -----
sound system is muted
    1 stereo
32768 samples
   16 samplebits
    1 submission_chunk
22050 speed
0xf52bd30 dma buffer
No background file.
----------------------
Sound memory manager started
Loading dll file ui.
Failed to load dll, looking for qvm.
Loading vm file vm/ui.qvm.
ui loaded in 2348480 bytes on the hunk
74 arenas parsed
32 bots parsed
--- Common Initialization Complete ---
Winsock Initialized
Opening IP socket: localhost:27960
Hostname: AMS-COMP
IP: 192.168.1.2
IP: 192.168.56.1
Working directory: f:\Downloads\Temp\Quake3
----- CL_Shutdown -----
RE_Shutdown( 1 )
Shutting down Vulkan subsystem
...destroying Vulkan window
...unloading Vulkan DLL
-----------------------
Vulkan: error code -4 returned by vkQueueSubmit(vk.queue, 1, &submit_info, vk.rendering_finished_fence)

**Comment by kennyalive** [comment]
Thanks for the report. Does this occur on each run?

**Comment by xtemp09** [comment]
Yes, every time. openGL version works, vkQuake works as well.

**Comment by kennyalive** [comment]
I can reproduce it now. The bug is reproduced on NVIDIA hardware and I use AMD GPU at the moment, that's why I didn't notice this earlier. Started to look at the problem.

**Comment by kennyalive** [comment]
The issue should be fixed in the latest release 1.2.
