### ISSUE TITLE
Crash with Vulkan backend on AMD Radeon HD 7800

### ISSUE THREAD

**Issue by Tarnyko** [artemalive/Quake-III-Arena#4]
Hi @kennyalive. First of all, thanks for the great work and for sharing !

quake3-ke crashes with Vulkan backend (OpenGL backend works OK) after redrawing first frame on Radeon HD 7800. VkQuake works OK.

Here is the log (**quake3-ke.exe +set r_renderAPI 1 +set logfile 2 +wait**) :

> logfile opened on Sun Nov 19 03:53:51 2017
> 
> ...detecting CPU, found generic
> 
> ------- Input Initialization -------
> Win32 mouse input initialized.
> ------------------------------------
> ----- Client Initialization -----
> ----- Initializing Renderer ----
> -------------------------------
> ----- Client Initialization Complete -----
> ----- R_Init -----
> Initializing Vulkan subsystem
> ...calling LoadLibrary('vulkan-1.dll'): succeeded
> ...setting fullscreen mode: 1920 1080 FS
> ...registered window class
> ...created window@0,0 (1920x1080)
> 
> Active 3D API: Vulkan
> Vk api version: 1.0.51
> Vk driver version: 4218880
> Vk vendor id: 0x1002 (Advanced Micro Devices, Inc.)
> Vk device id: 0x679E
> Vk device type: DISCRETE_GPU
> Vk device name: AMD Radeon HD 7800 Series
> 
> MODE: 3, 1920 x 1080 fullscreen
> GAMMA: hardware w/ 0 overbright bits
> texturemode: GL_LINEAR_MIPMAP_NEAREST
> picmip: 1
> texture bits: 0
> ----- finished R_Init -----
> 
> ------- sound initialization -------
> Initializing DirectSound
> ------------------------------------
> ----- Sound Info -----
> sound system is muted
>     1 stereo
> 32768 samples
>    16 samplebits
>     1 submission_chunk
> 22050 speed
> 0xa0350090 dma buffer
> No background file.
> ----------------------
> Sound memory manager started
> Loading vm file vm/ui.qvm.
> ui loaded in 2348480 bytes on the hunk
> 35 arenas parsed
> 32 bots parsed
> --- Common Initialization Complete ---
> Winsock Initialized
> Opening IP socket: localhost:27960
> Hostname: PC
> IP: 127.0.0.1
> Working directory: C:\Users\Tarnyko\quake3

Then first frame -title screen- shows with cursor, cursor is immediately stuck and Windows kills it after 5 seconds.
Not sure how I could drop more detailed logs for you.

**Comment by kennyalive** [comment]
Hi @Tarnyko. Thanks for the report. I'll take a look at this but it will take some time. I'll be able to test on AMD hardware in a week or two.

**Comment by kennyalive** [comment]
Hi @Tarnyko . Did you run the game in fullscreen mode?

**Comment by kennyalive** [comment]
Fixed by https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition/commit/abe1efe3aaa70ee625e210a5dd25640c872f8906.
