### ISSUE TITLE
Compile Error in Debug x86 Build

### ISSUE THREAD

**Issue by Andreyogld3d** [artemalive/Quake-III-Arena#6]
Visual C++ 2017 compile Error:

..\src\engine\renderer\vk.cpp(659): error C2440: '=': cannot convert from 'VkBool32 (__cdecl *)(VkDebugReportFlagsEXT,VkDebugReportObjectTypeEXT,uint64_t,::size_t,int32_t,const char *,const char *,void *)' to 'PFN_vkDebugReportCallbackEXT'

to fix (vk_vpp):
....
static VkBool32 VKAPI_PTR debug_callback(VkDebugReportFlagsEXT flags, VkDebugReportObjectTypeEXT .....

desc.pfnCallback = debug_callback;

**Comment by kennyalive** [comment]
Updated. Not sure why do you have a compilation error. I also use vs 2017. The macro is expanded to __stdcall which is ignored on x64.

**Comment by kennyalive** [comment]
I'm closing the issue since I can't see how even before the fix the provided code could cause a compilation error (in debug configuration). Please ensure that you have the latest VS updates.

**Comment by Andreyogld3d** [comment]
Thanks, 
Error was reproduced for x86 build(I added the new configuration). For x64, i have no error.
I'm using Visual Studio 2017 15.5.3(last update)

**Comment by kennyalive** [comment]
Ok. It's clear now. Thanks for reporting. x86 is not supported by this codebase. I minimized the number of supported configurations since I'm limited in time that I can devote to this project and especially to testing.
