### ISSUE TITLE
Can't change graphics setting in OpenGL mode.

### ISSUE THREAD

**Issue by Jimmy-Z** [artemalive/Quake-III-Arena#7]
When I hit the "accept" button:
````
...
RE_Shutdown( 1 )
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying opengl window
...shutting down QGL
...unloading OpenGL DLL
Hunk_Clear: reset the hunk ok
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
Initializing OpenGL subsystem
...initializing QGL
...calling LoadLibrary('libGL.so.1'): failed
----- CL_Shutdown -----
RE_Shutdown( 1 )
-----------------------
QGL_Init - could not load OpenGL driver
````
I don't know why it tries to load "libGL.so.1" instead of "opengl32", I searched in the source tree, no file contains that string. I tried to set a breakpoint on the line setting r_glDriver in ui_video.c but apparently that file is not used in the exe built.

Sorry I'm new to q3.

**Comment by kennyalive** [comment]
Hi Jimmy-Z. 
"libGL.so.1" is defined in unix platform code in original q3 codebase. If the game tries to load this file it means that r_glDriver is set to that value. It could be specified in some config file in your Q3 folder.  You can try to start the game from command line like this: quake3-ke-1.3.exe +set r_glDriver opengl32. If this doesn't help let me know.

In general it's not an issue of this project, the program behaves correctly and reports that driver dll specified in configuration does not exists. Probably if you run original quake3.exe it will report similar error. So I'm closing this.

**Comment by Jimmy-Z** [comment]
If it's in the config file, it will crash immediately upon launch.

It even survive a `vid_restart`, which loads "opengl32.dll" as expected, it only happens if I change graphics setting in the GUI and hit the "apply" button.

**Comment by kennyalive** [comment]
Thanks for clarification, I can reproduce it now.

**Comment by kennyalive** [comment]
Fixed in https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition/commit/2d62ff47df207f7f9593622f3f3b9322fbfa81e6.
Corresponding executable:
https://ci.appveyor.com/project/kennyalive/quake-iii-arena-kenny-edition/build/1.1.76/artifacts

**Comment by Jimmy-Z** [comment]
IMHO this is an ugly workaround(no offense), why does it try to load libGL.so.1 in the first place...

**Comment by kennyalive** [comment]
I agree but it's the best we can do here. Original Q3 does the same. I tried to explain in commit message why it happens - this value is returned from ui.qvm (q3 ui logic) and it's not part of the engine (quake3.exe), so unfortunately this can not be fixed on the engine side.

The issue in game code is fixed in this project so if you compile qvm manually and use them instead of qvm provided by q3 distribution that problem won't appear. But the goal is to make this modified engine to work as smoothly as possible with original q3 data.
